# Base configs
baseurl: "https://agebeyaw.github.io/bahirdar-photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Bahirdar Photography"
subtitle: "Shooting the birds of Bahirdar"
author: "Bahirdar Photography"
header:
 title: "Bahirdar"
 subtitle: "Photography"
footer:
 name: "Hey there,"
 bio: "Out and about in Bahirdar, #Ethiopia - shooting everything but mostly birds for a book on The Birds of Bahirdar."
 github: "Email <a href=\"mailto:info@bahirdar-photography.com\">info@bahirdar-photography.com</a>"
web_design: "<a href=\"https://twitter.com/angeboy\">Anteneh Gebeyaw</a>"
social_urls:
#  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://twitter.com/BDR_Photography"
#  instagram: "https://www.instagram.com/ram_patra"
#  dribbble: "https://dribbble.com/rampatra"
#  linkedin: "https://in.linkedin.com/in/ram-patra"
#  github: "https://www.github.com/rampatra"
